Repository UKHomeOffice/core-cloud-multiple-static-sites-terraform, pull requests merged in 2025-02, with the labels that each got.

#4 update to use latest module version, for required tags
  main.tf
Labels: minor

#5 bump to match patch version
  main.tf
Labels: patch

#6 consume latest TF with product and component params
  main.tf
Labels: patch

#7 bump ver
  main.tf
Labels: patch

#8 bump ver
  main.tf
Labels: patch

#9 configuring waf for static site test
  main.tf
  variables.tf
Labels: major

#10 static sites v2
  main.tf
Labels: patch

#11 Revert & v0.2.0
  main.tf
Labels: patch

#12 static site v0.2.1
  main.tf
Labels: patch

#14 waf 0.4.5
  main.tf
Labels: patch

#16 scope cloudfront
  main.tf
Labels: patch

#17 waf_acl_id to waf_acl_arn
  main.tf
Labels: patch
